# Generated by Django 3.0.5 on 2020-04-20 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_submission_author'),
        ('reviews', '0002_auto_20200420_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission'),
        ),
    ]
