# Generated by Django 3.0.5 on 2020-04-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0005_auto_20200419_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_time', models.CharField(choices=[('5-10', '5-10 minutes'), ('10-30', '10-30 minutes'), ('30-60', '30-60 minutes'), ('60+', '60 minutes +')], max_length=10)),
                ('genres', models.ManyToManyField(blank=True, to='submissions.Genre')),
                ('themes', models.ManyToManyField(blank=True, to='submissions.Theme')),
                ('writing_types', models.ManyToManyField(blank=True, to='submissions.WritingType')),
            ],
        ),
    ]
