# Generated by Django 3.0.5 on 2020-04-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_auto_20200420_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='puser',
            new_name='user',
        ),
    ]
