# Generated by Django 3.0.5 on 2020-04-18 20:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('review_time', models.CharField(choices=[('5-10', '5-10 minutes'), ('10-30', '10-30 minutes'), ('30-60', '30-60 minutes'), ('60+', '60 minutes +')], max_length=10)),
                ('min_review_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('max_review_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('message_to_reader', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WritingTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_type', models.CharField(choices=[('poetry', 'Poetry'), ('scripts', 'Scripts'), ('longform', 'Long Form')], max_length=10)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes', models.CharField(choices=[('lgbtq', 'LGBTQ+'), ('color', 'Being a person of color'), ('family', 'Family')], max_length=10)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(choices=[('horror', 'Horror'), ('romance', 'Romance'), ('comedy', 'Comedy'), ('action', 'Action'), ('legal', 'Legal')], max_length=10)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.Submission')),
            ],
        ),
    ]
