# Generated by Django 3.0.5 on 2020-04-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('horror', 'Horror'), ('romance', 'Romance'), ('comedy', 'Comedy'), ('action', 'Action'), ('legal', 'Legal')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Genres',
        ),
        migrations.AddField(
            model_name='submission',
            name='genres',
            field=models.ManyToManyField(blank=True, to='submissions.Genre'),
        ),
    ]
