# Generated by Django 3.0.5 on 2020-04-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_auto_20200420_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='genres',
        ),
        migrations.AddField(
            model_name='submission',
            name='genres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='submissions.Genre'),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='themes',
        ),
        migrations.AddField(
            model_name='submission',
            name='themes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='submissions.Theme'),
        ),
        migrations.RemoveField(
            model_name='submission',
            name='writing_types',
        ),
        migrations.AddField(
            model_name='submission',
            name='writing_types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='submissions.WritingType'),
        ),
    ]
